Issue #KN-50 feat: Angular migration from version 11 to 12
project-sunbird/sunbird-pdf-player pull request #83
Opened 2022-08-09 09:37 UTC by gouravmore

[Issue #KN-50 feat: Angular migration from version 9 to 12](https://github.com/project-sunbird/sunbird-pdf-player/commit/c4a4a0aeba42c222a2dbee6bf2d20774c2d89fb5)

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

### Type of change

Please choose appropriate options.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

### How Has This Been Tested?

Please describe the tests that you ran to verify your changes in the below checkboxes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Ran Test A
- [ ] Ran Test B

**Test Configuration**:
* Software versions:
* Hardware versions:

### Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

2022-08-09 11:45 UTC, HarishGangula requested changes

2022-08-10 09:17 UTC, gouravmore commented on angular.json
> +            "optimization": false,
It's got auto updated from migration script of 11 to 12

2022-08-10 09:26 UTC, HarishGangula commented on angular.json
> +            "optimization": false,
Check what is the correct value for each and update here about it

2022-08-10 11:04 UTC, gouravmore commented on angular.json
> +            "optimization": false,
It is newly added by migration script, correct values are true for all but it is already added in production configuration line https://github.com/project-sunbird/sunbird-pdf-player/pull/83/files#diff-2d2675bb4687601a5c7ccf707455132f90f3516a33716185687e5c41df59ac7dL55 to line to https://github.com/project-sunbird/sunbird-pdf-player/pull/83/files#diff-2d2675bb4687601a5c7ccf707455132f90f3516a33716185687e5c41df59ac7dL63

2022-08-10 11:04 UTC, gouravmore commented on angular.json
> +            "optimization": false,
There is no change in existing code

2022-08-11 09:06 UTC, merged